format_version: 10
pipelines:
  Ansible_FT_AWS:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    environment_variables:
      playbook_name: ft_playbook_v0.7.yml
      archive_flag: OFF
      file_loc: C:\src_loc\
      tmp_loc: /home/ubuntu/ansible/tmp/
      target_loc: C:\{{ inventory_hostname }}\
      file_size: 2k
    secure_variables:
    materials:
      git-e912034:
        git: https://github.com/Rajasekar1990/Ansible_AWS.git
        username: Rajasekar1990
        shallow_clone: false
        auto_update: true
        branch: main
        password: Shiva2889$
    stages:
    - Agent_Check:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: manual
          allow_only_on_success: false
        jobs:
          Agent_validate:
            timeout: 0
            tasks:
            - exec: 
                arguments:
                - Ready to execute ansible playbook ${playbook_name}
                command: echo
                run_if: passed
    - File_Transfer:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: true
        jobs:
          Run_FT_Playbook:
            timeout: 0
            artifacts:
            - build:
                source: ansible_log*
                destination: ''
            tasks:
            - exec: 
                arguments:
                - -c
                - cd /
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - cd /home/ubuntu/ansible
                command: /bin/bash
                run_if: passed
            - exec:
                arguments:
                - -c
                - ansible-playbook -i inventory ${playbook_name} -vv
                command: /bin/bash
                run_if: passed