format_version: 10
pipelines:
  Ansible_Ctrllr_DB_Playbook:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    environment_variables:
      Playbook_name: 'mssql_db_run_playbook_gocd_v0.4.1.yml'
      mssql_login_host: '172.31.45.40'
      mssql_login_user: 'target1'
      mssql_db: 'test_db'
      mssql_port: 1433
      sql_srcpath: 'sql_stmts/'
      sql_dirpath: 'sql_results'
      Ansible_logpath: 'ansible_log.log'
      # Vault_password_file: '.secrets.yml'
    secure_variables:
      # Valut_secret_Key: AES:2cRYJgLsJSi243QsN9eWqQ==:TGoO0cRXhheJGjylX6LZIA==
      mssql_login_password: AES:2G+TB6ba9zA+B6ejy8NHwQ==:y2aCvK75HxpL1ufbejdnSQ==
    materials:
      git-e912034:
        git: https://github.com/Rajasekar1990/Ansible_AWS.git
        username: Rajasekar1990
        shallow_clone: false
        auto_update: true
        branch: main
        password: AES:tyM62jnM4IMK9AMLfWYHmg==:l8lHguVKMszpxWcJoM3ayA==
        # destination: gocd_ansible
    stages:
    - MSSQL_DB_SQL_Stmts:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          # type: success
          # allow_only_on_success: true
          type: manual
          allow_only_on_success: true
        jobs:
          Run_DB_Playbook:
            timeout: 0
            artifacts:
            - build:
                source: ansible_log*
                destination: ''
            - build:
                source: sql_stmts*
                destination: ''
            - build:
                source: sql_results*
                destination: ''
            - build:
                source: sqlfilename_list*
                destination: ''
            - build:
                source: variables.yml
                destination: ''
            - build:
                source: ansible.cfg
                destination: ''
            tasks:
            - exec:
                arguments:
                - -c
                - echo user logged in as $(whoami)
                command: /bin/bash
                runif: passed
            - exec:
                arguments:
                - Db_Variables_Yml_Update
                command: make
                run_if: passed
            - exec:
                arguments:
                - MSSQL_Db_Ctrllr_Playbook
                command: make
                # working_directory: gocd_ansible
                run_if: passed